name: Docker Build & Deploy

on:
  push:
    branches:
      - main


    
jobs:
  build:
    runs-on: macos-13

    steps:
    - name: build
      run: echo "build"
    - name: Setup Docker on macOS
      uses: douglascamata/setup-docker-macos-action@v1-alpha
    - name: check
      run: docker version
        
