name: Docker Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [prereleased,published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: build
      run: echo "build"

  deploy-integration-and-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Integration and Staging
      run: |
        # Deployment scripts for integration (int) and staging (stg)
        echo "Deploy to Integration and Staging"

  deploy-pre-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true

    steps:
    - name: Deploy to Pre-production
      run: |
        # Deployment script for pre-production (ppd)
        echo "Deployment script for pre-production (ppd)"

  deploy-production:
    needs: deploy-pre-production
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && github.ref_name == 'refs/tags/v*'

    steps:
    - name: Deploy to Production
      run: |
        # Deployment script for production (prd)
        echo "Deployment script for production (prd)"
