name: Docker Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your_image_name .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push your_image_name

  deploy-integration-and-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Integration and Staging
      run: |
        # Deployment scripts for integration (int) and staging (stg)

  deploy-pre-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Pre-production
      run: |
        # Deployment script for pre-production (ppd)

  deploy-production:
    needs: deploy-pre-production
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && github.ref == 'refs/tags/v*'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        # Deployment script for production (prd)
