name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: install acme
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
      run: |
        # git clone https://github.com/acmesh-official/acme.sh.git
        # cd ./acme.sh
        # ./acme.sh --install -m zouaoui.faycal.p@gmail.com
        # env
        # /home/runner/.acme.sh/acme.sh --issue  -d wedreamteam.com  --dns dns_aws --keylength 4096 --server letsencrypt
        # cp /home/runner/.acme.sh/wedreamteam.com/wedreamteam.com.cer wedreamteam.com.pem
        # cp /home/runner/.acme.sh/wedreamteam.com/wedreamteam.com.key .
        openssl req -config cert.conf -newkey rsa:2048 -nodes -keyout wedreamteam.com.key -x509 -days 365 -out wedreamteam.com.pem


      
    - name: Build the Docker image
      run: cd $GITHUB_WORKSPACE &&  docker build . --file Dockerfile --tag tls:$(date +%s)

    - name: push to ecr 
      run: |
        aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 785747403946.dkr.ecr.eu-west-3.amazonaws.com
        docker tag tls:$(date +%s) 785747403946.dkr.ecr.eu-west-3.amazonaws.com/tls:$(date +%s)
        docker push 785747403946.dkr.ecr.eu-west-3.amazonaws.com/tls:$(date +%s)

    - name: restart task   
      run: aws ecs  update-service --cluster tls --service tls-svc --force-new-deployment

