name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3


    - name: install acme
      env: # Or as an environment variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
      run: |
        git clone https://github.com/acmesh-official/acme.sh.git
        cd ./acme.sh
        ./acme.sh --install -m zouaoui.faycal.p@gmail.com
        env
        /home/runner/.acme.sh/acme.sh --issue  -d wedreamteam.com  --dns dns_aws --keylength 4096 --server letsencrypt
        cp /home/runner/.acme.sh/wedreamteam.com/wedreamteam.com.cer wedreamteam.com.pem
        cp /home/runner/.acme.sh/wedreamteam.com/wedreamteam.com.key .

      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tls:$(date +%s)
