name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3

    - name: insatall acme
      run: |
        git clone https://github.com/acmesh-official/acme.sh.git
        cd ./acme.sh
        ./acme.sh --install -m zouaoui.faycal.p@gmail.com

      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag tls:$(date +%s)
